### ISSUE TITLE
Maddison Project Database 2018 released

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [expersso/maddison#1]
I just stumbled over your nice `R` package `maddison`! Since you asked to remind you of newer releases in [the vignette's disclaimer](https://cran.r-project.org/web/packages/maddison/vignettes/maddison_project_database.html): 2018 saw the release of a new version: [https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2018](https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2018). It'd be super nice if you could update your package accordingly. :+1:

**Comment by briatte** [comment]
Just stopping here to say the same thing and subscribe to the issue thread :)

Thanks for all your packages, @expersso. I also wonder whether some of them could/should join the [rOpenGov](https://github.com/rOpenGov) collective?

**Comment by briatte** [comment]
Thanks!
